# These are supported funding model platforms

github: # [YOUR-GITHUB-USERNAME]
patreon: # [YOUR-PATREON]
open_collective: # [YOUR-COLLECTIVE]
ko_fi: # [YOUR-KOFI]
custom: # ['https://your-website.com']

# Uncomment and fill in your preferred funding options
# This file enables the "Sponsor" button on your GitHub repo
